// Schema do PostgreSQL. Equivale ao SQLite depois de todas as migrações até POSTGRES_SCHEMA_VERSION.
// Mudou o schema? Adicione a migração nos dois: em SQLITE_MIGRATIONS (migrations.ts) e em POSTGRES_MIGRATIONS abaixo.
// As datas ficam como texto ISO em UTC, igual ao SQLite — o código compara e ordena como texto.

const NOW = `(to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))`;
const ID = 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';

export const POSTGRES_SCHEMA_VERSION = 6;

export const POSTGRES_SCHEMA = `
CREATE TABLE people (
  id         ${ID},
  name       TEXT NOT NULL,
  email      TEXT,
  color      TEXT NOT NULL,
  is_agent   INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ${NOW}
);

CREATE TABLE projects (
  id         ${ID},
  name       TEXT NOT NULL,
  color      TEXT NOT NULL,
  folder     TEXT,
  position   DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  git_state  TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE boards (
  id               ${ID},
  name             TEXT NOT NULL,
  description      TEXT NOT NULL DEFAULT '',
  position         DOUBLE PRECISION NOT NULL DEFAULT 0,
  next_item_number INTEGER NOT NULL DEFAULT 1,
  settings         TEXT NOT NULL DEFAULT '{}',
  created_at       TEXT NOT NULL DEFAULT ${NOW},
  updated_at       TEXT NOT NULL DEFAULT ${NOW},
  project_id       INTEGER REFERENCES projects(id) ON DELETE CASCADE
);
CREATE INDEX idx_boards_project ON boards(project_id, position);

CREATE TABLE board_groups (
  id         ${ID},
  board_id   INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  color      TEXT NOT NULL,
  position   DOUBLE PRECISION NOT NULL DEFAULT 0,
  collapsed  INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ${NOW}
);
CREATE INDEX idx_groups_board ON board_groups(board_id, position);

CREATE TABLE board_columns (
  id         ${ID},
  board_id   INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  type       TEXT NOT NULL,
  settings   TEXT NOT NULL DEFAULT '{}',
  width      INTEGER NOT NULL DEFAULT 140,
  position   DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ${NOW}
);
CREATE INDEX idx_columns_board ON board_columns(board_id, position);

CREATE TABLE items (
  id              ${ID},
  board_id        INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  group_id        INTEGER NOT NULL REFERENCES board_groups(id) ON DELETE CASCADE,
  number          INTEGER NOT NULL,
  name            TEXT NOT NULL,
  position        DOUBLE PRECISION NOT NULL DEFAULT 0,
  kanban_position DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL DEFAULT ${NOW},
  updated_at      TEXT NOT NULL DEFAULT ${NOW},
  deleted_at      TEXT
);
CREATE INDEX idx_items_group ON items(group_id, position);
CREATE INDEX idx_items_board ON items(board_id, deleted_at);
CREATE UNIQUE INDEX idx_items_number ON items(board_id, number);

CREATE TABLE item_values (
  item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  column_id  INTEGER NOT NULL REFERENCES board_columns(id) ON DELETE CASCADE,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT ${NOW},
  PRIMARY KEY (item_id, column_id)
);
CREATE INDEX idx_values_column ON item_values(column_id);

CREATE TABLE updates (
  id         ${ID},
  item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  author_id  INTEGER REFERENCES people(id) ON DELETE SET NULL,
  body       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);
CREATE INDEX idx_updates_item ON updates(item_id, created_at);

CREATE TABLE activity (
  id         ${ID},
  board_id   INTEGER NOT NULL REFERENCES boards(id) ON DELETE CASCADE,
  item_id    INTEGER REFERENCES items(id) ON DELETE SET NULL,
  item_name  TEXT,
  actor_id   INTEGER REFERENCES people(id) ON DELETE SET NULL,
  source     TEXT NOT NULL DEFAULT 'user',
  action     TEXT NOT NULL,
  data       TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT ${NOW}
);
CREATE INDEX idx_activity_board ON activity(board_id, id);
CREATE INDEX idx_activity_item ON activity(item_id, id);

CREATE TABLE commits (
  project_id   INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  hash         TEXT NOT NULL,
  subject      TEXT NOT NULL,
  body         TEXT NOT NULL DEFAULT '',
  author_name  TEXT NOT NULL,
  author_email TEXT NOT NULL DEFAULT '',
  committed_at TEXT NOT NULL,
  repo         TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (project_id, hash)
);

CREATE TABLE item_commits (
  item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL,
  hash       TEXT NOT NULL,
  closed     INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  PRIMARY KEY (item_id, hash)
);
CREATE INDEX idx_item_commits_project ON item_commits(project_id, hash);

CREATE TABLE subitems (
  id         ${ID},
  item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  done       INTEGER NOT NULL DEFAULT 0,
  position   DOUBLE PRECISION NOT NULL DEFAULT 0,
  done_at    TEXT,
  done_by    INTEGER REFERENCES people(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT ${NOW},
  updated_at TEXT NOT NULL DEFAULT ${NOW}
);
CREATE INDEX idx_subitems_item ON subitems(item_id, position);

CREATE TABLE code_todos (
  project_id  INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  item_id     INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  path        TEXT NOT NULL,
  line        INTEGER NOT NULL,
  col         INTEGER NOT NULL DEFAULT 1,
  tag         TEXT NOT NULL,
  text        TEXT NOT NULL,
  imported_at TEXT NOT NULL DEFAULT ${NOW},
  removed_at  TEXT,
  PRIMARY KEY (project_id, fingerprint)
);
CREATE INDEX idx_code_todos_item ON code_todos(item_id);
`;

/** Migrações posteriores ao schema acima: versão → SQL. */
export const POSTGRES_MIGRATIONS: [version: number, sql: string][] = [];
